site_name: Financial Planner
site_description: Financial Planning Tools

repo_url: https://github.com/jcmullwh/financial_planner
repo_name: jcmullwh/financial_planner

theme:
    name: material
    icon:
        logo: material/library
    palette:
        # Palette toggle for automatic mode
        - media: "(prefers-color-scheme)"
          toggle:
            icon: material/brightness-auto
            name: Switch to light mode

        # Palette toggle for light mode
        - media: "(prefers-color-scheme: light)"
          scheme: default
          primary: blue grey
          accent: light blue
          toggle:
            icon: material/brightness-7
            name: Switch to dark mode

        # Palette toggle for dark mode
        - media: "(prefers-color-scheme: dark)"
          scheme: slate
          primary: blue grey
          accent: light blue
          toggle:
            icon: material/brightness-4
            name: Switch to light mode

markdown_extensions:
    - toc:
        permalink: true
    - pymdownx.highlight:
        anchor_linenums: true
    - pymdownx.tasklist:
        custom_checkbox: true
    - pymdownx.inlinehilite
    - pymdownx.snippets
    - pymdownx.superfences

plugins:
    - search
    - mkdocstrings:
        handlers:
            python:
                import:
                    - https://docs.python.org/3.9/objects.inv
                options:
                    docstring_style: google

watch:
    - docs
    - src/financial_planner

nav:
    - About: index.md
    - Project Plan:
        - "Project Overview": "project_plan/project_overview.md"
    - Tutorials:
        - "Index": "tutorials/index.md"
        - "Getting Started": "tutorials/getting_started.md"
        - "First Simulation": "tutorials/first_simulation.md"
    - How-To Guides:
        - "Index": "how_to/index.md"
        - "Update Inflation Rate": "how_to/update_inflation_rate.md"
        - "Adjust Tax Rate": "how_to/adjust_tax_rates.md"
        - "Adding Members": "how_to/adding_members.md"
    - Reference:
        - "API Reference": "reference/index.md"
    - Explanation:
        - "Index": "explanation/index.md"
        - "Architecture Overview": "explanation/architecture.md"
        - "Design Choices": "explanation/design_choices.md"
